Clean code
evinracher/pokemon-app-demo pull request #1
Opened 2020-09-20 02:13 UTC by evinracher

Some problems.

2020-09-21 18:38 UTC, hackeo1 requested changes
- comments get outdated easily, use more descriptive variables and function names instead
- add an extra line between the component and the imports
- the calls for listing and details must be done in different actions (only when needed)

2020-09-21 18:38 UTC, hackeo1 commented on src/Utils.js
> +      res += " " + styles[classname];
use single quotes

2020-09-21 18:38 UTC, hackeo1 commented on src/Utils.js
> +// Helper functions:
use a different file instead of adding a comment

2020-09-21 18:38 UTC, hackeo1 commented on src/Utils.js
> +export async function getOnePokemon(name) {
the name of the function should explain what it does without needing a comment

2020-09-21 18:38 UTC, hackeo1 commented on src/Utils.js
> +    if (gender > 4) {
instead of adding extra ifs inside organize the logic so it takes first the inner scenario and the other one in an else if

2020-09-21 18:38 UTC, hackeo1 commented on src/components/Card.js
> +    isShowing: state.global.isShowing, // delete
this comment confuses me, is it to delete this line?

2020-09-21 18:38 UTC, hackeo1 commented on src/components/Card.js
> +  const { showThisPokemon } = props; // state functions
remove comments

2020-09-21 18:38 UTC, hackeo1 commented on src/components/Graphics.js
> +    new Chart(ctx, {
this creates a new instance each time an is not store anywhere, it might be necessary to dispose of the previous one, check it out

2020-09-21 18:38 UTC, hackeo1 commented on src/components/Info/PokemonDetail.js
> +          <button className={details['button--compare']}
compare is not a style description, when using BEM it is expected that whatever follows -- is a description of the style of the element

2020-09-21 18:38 UTC, hackeo1 commented on src/components/Main.js
> +} from "react-router-dom";
single quotes

2020-09-21 18:38 UTC, hackeo1 commented on src/components/Nav.js
> +import Search from "./Search"
single quotes

2020-09-21 18:38 UTC, hackeo1 commented on src/components/Pokemons.js
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
don't use eslint disable comments

2020-09-21 18:38 UTC, hackeo1 commented on src/components/Search.js
> +    let name = event.target.value.trim().replace(/\s+/g, "-");
single quotes

2020-09-21 18:38 UTC, hackeo1 commented on src/redux/reducers/globalReducer.js
> +  nextURL: initialURL
why do you store the whole url instead of the parameters?

2020-09-21 18:38 UTC, hackeo1 commented on src/redux/reducers/globalReducer.js
> +const initialURL = 'https://pokeapi.co/api/v2/pokemon/?offset=0&limit=20';
remove comment

2020-09-21 18:38 UTC, hackeo1 commented on src/redux/actions/globalActions.js
> +        return getOnePokemon(result.url);
this information should only be called when the user requires it (when seeing details)
this is killing the server with too many calls every time the page loads

2020-09-21 18:38 UTC, hackeo1 commented on src/styles/Card.module.css
> +@media(min-width: 577px) {}
remove

2020-09-21 18:38 UTC, hackeo1 commented on src/styles/Info/Comparison.module.css
> +  grid-template-columns: 33% 33% 33%;
use 1fr in each instead

2020-09-21 18:38 UTC, hackeo1 commented on src/styles/Info/Comparison.module.css
> +.info__row p {
use classes

2020-09-21 18:38 UTC, hackeo1 commented on src/styles/Info/Details.module.css
> +  color: white;
use varaible

2020-09-21 18:38 UTC, hackeo1 commented on src/styles/Pokemons.module.css
> +    width: fit-content;
don't use named values for width or height, except for auto

2020-09-21 18:38 UTC, hackeo1 commented on src/styles/Search.module.css
> +    width: fit-content;
don't use named values for width or height, except for auto

2020-09-21 18:38 UTC, hackeo1 commented on src/styles/Pokemons.module.css
> +.loader div {
use classes

2020-09-21 19:11 UTC, evinracher commented on src/components/Card.js
> +    isShowing: state.global.isShowing, // delete
I forget to delete this

2020-09-21 19:14 UTC, evinracher commented on src/redux/reducers/globalReducer.js
> +  nextURL: initialURL
Because I use the nextUrl property of the response, so I don't need to manage the current offset

2020-09-22 15:28 UTC, hackeo1 requested changes
- the Utils file contains different calls and there are some utilities, take out the calls functions and include them in a file that is easy to understand what it does by its name
- avoid the use of px in width

2020-09-22 15:28 UTC, hackeo1 commented on src/Utils.js
> +  let pokemon = await fetchOnePokemon(name);
is the parameter the name of the pokemon or is it the url? it is used here as if the name and url were the same thing

2020-09-22 15:28 UTC, hackeo1 commented on src/components/Graphics.js
> +              color: 'rgba(0, 0, 0)',
rgba missing the third paramenter

2020-09-22 15:28 UTC, hackeo1 commented on src/styles/Info/Comparison.module.css
> +  width: 186px;
use rem

2020-09-22 15:28 UTC, hackeo1 commented on src/styles/Info/Details.module.css
> +  width: 186px;
use rem

2020-09-22 15:28 UTC, hackeo1 commented on src/styles/Search.module.css
> +  border: 1px solid red;
use variable

2020-09-22 16:32 UTC, evinracher commented on src/styles/Search.module.css
> +  border: 1px solid red;
This code shouldn't be there

2020-09-22 16:38 UTC, evinracher commented on src/Utils.js
> +  let pokemon = await fetchOnePokemon(name);
It is the url

2020-09-22 17:00 UTC, hackeo1 approved these changes

2020-09-22 19:34 UTC, merged